# Pharmacophore

Generating a pharmacophore from any of the available methods
returns a `t2fpharm.pharm.Pharmacophore` object
that provides different methods and attributes
to analyze, process, and visualize the generated pharmacophore.

In [4]:
import t2fpharm
import t2fpharm_study  # To obtain a pre-generated pharmacophore

Here, we use pre-generated `Pharmacophore` objects for brevity:

In [17]:
manager = t2fpharm_study.manager()
PDB_ID = "1AQ1"
# Pharmacophore generated by the `largest_peaks` method
pharm_lp: t2fpharm.pharm.Pharmacophore = manager.job_pharmacophore(
    job_name="grid_search-lp-1",
    pdb_id=PDB_ID,
    job_idx=1721
)
# Pharmacophore generated by the `cnn` method
pharm_cnn: t2fpharm.pharm.Pharmacophore = manager.job_pharmacophore(
    job_name="grid_search-cnn-1",
    pdb_id=PDB_ID,
    job_idx=1978
)
# Pharmacophore generated from the receptor–ligand complex
pharm_complex: t2fpharm.pharm.Pharmacophore = manager.ligand_pharmacophore(PDB_ID)

## Features

Pharmacophore features are stored as a `pandas.DataFrame`
and can be accessed from the `features` property:

In [12]:
pharm_lp.features[:5]

,instance,type,label,center,radius,value
0,0,OA,"(19, 64, 49)","[-4.930499935150146, 33.254500961303705, 13.31...",1.1625,-0.98
1,0,OA,"(26, 57, 41)","[-2.8304999351501463, 31.154500961303707, 10.9...",1.1625,-0.923
2,0,OA,"(40, 57, 27)","[1.3695000648498539, 31.154500961303707, 6.714...",1.1625,-0.832
3,0,OA,"(50, 49, 28)","[4.369500064849854, 28.75450096130371, 7.01449...",1.1625,-0.733
4,0,OA,"(66, 36, 20)","[9.169500064849855, 24.854500961303707, 4.6144...",1.1625,-0.701

The DataFrame contains at least the following columns:
- `instance`: An identifier for the feature instance,
  e.g., for when the pharmacophore is derived
  from multiple receptors or ligands.
  If only a single instance is generated, this will be 0 for all features.
- `type`: A string representing the feature type,
   e.g., "hbond_donor", "hbond_acceptor", "hydrophobic", etc.
- `label`: An identifier for different features of the same type
   within the same instance. That is, for each unique (`instance`, `type`) pair,
   each feature has a unique label.
   Each feature in the whole pharmacophore can thus be uniquely identified
   by its (`instance`, `type`, `label`) triplet.
   When the pharmacophore is generated using the `largest_peaks` method,
   the labels correspond to the grid index of the selected points.
- `center`: A sequence of three real numbers representing
   the 3D coordinates of the feature.
- `radius`: A non-negative real number representing the feature radius.
   The radius represents the uncertainty of the feature center.
   When the pharmacophore is generated using the `largest_peaks` method,
   - if a filter function is used, the radius is equal to the filter radius for each type.
   - If no filter function is used, the radius is equal to the grid point radius
     (i.e., half of the grid spacing).
  
  When the pharmacophore is generated using the `cnn` method,
  the radius is equal radius of the cluster, as specified by the method's `radius_type` argument.
- `value`: Value of the corresponding field at `center`.
  This is only available for target-based pharmacophores.

In [18]:
pharm_cnn.features[:5]

,instance,type,label,center,radius,value,n_members
0,0,HD,1,"[7.303346218696005, 27.246808653611417, 4.0468...",3.123256,-0.573,195
1,0,HD,2,"[2.966840490381764, 23.774181812367537, 11.897...",2.572247,-0.579,188
2,0,HD,3,"[0.3585411607402644, 32.42025438596123, 6.4494...",1.801207,-0.623,146
3,0,HD,4,"[1.1656165697042231, 26.293335912760018, 13.06...",1.557236,-0.622,103
4,0,HD,5,"[-2.62943610536291, 25.310883940027107, 14.543...",2.139163,-0.597,94

## Visualization

The pharmacophore can be visualized using the `display()` method.
The feature radii for visualization is taken from the `features` DataFrame,
unless `override_radius` is set to True:

In [14]:
pharm_lp.display(
    default_radius=1,
    overdide_radius=True
)

NGLWidget(gui_style='ngl')